routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.login');
})->name("admin.login");



// protected routes
Route::group(['middleware' => 'auth'], function() {
    
    /* Dashbaord routes */
    Route::resource('/dashboard', 'DashboardController');
    /* Dashbaord routes */

    /* Reports route */
    Route::resource('/reports', 'EmployeeReportController');
    /* Reports route */

});

resources/views/includes/footer.blade.php
<template>
    <div>
        <div class="row footer-wrap no-gutters align-items-center">

            <div class="col-md-4 col-12 start">
                Arimac Digital @ 2019 All Rights Reserved
            </div>
            <div class="col-md-4 col-12 text-center middle">Privacy Policy | Legal | Terms of Sale</div>
            <div class="col-md-4 col-12 d-flex justify-content-end end">
                <div class="follow-us align-self-center mr-1">Follow us on</div>
                <div class="icon mx-2"><a href=""><span class="helper"></span><i class="fab fa-facebook-f"></i></a></div>
                <div class="icon mx-2"><a href=""><span class="helper"></span><i class="fab fa-youtube"></i></a></div>
                <div class="icon mx-2"><a href=""><span class="helper"></span><i class="fab fa-instagram"></i></a></div>
                <div class="icon mx-2"><a href=""><span class="helper"></span><i class="fab fa-linkedin-in"></i></a></div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: "Footer"
    }
</script>

<style scoped>

</style>

resources/views/includes/head.blade.php
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="csrf-token">

{{-- Favicon --}}
<link rel="shortcut icon" href="{{ asset('images/favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ asset('images/favicon.ico') }}" type="image/x-icon">


<link rel="stylesheet" href="{{ asset('css/app.css') }}">
{{--sweetalert2--}}
<link rel="stylesheet" href="{{ asset('css/sweetalert2.min.css') }}" >
<script src="{{ asset('js/sweetalert2.min.js') }}"></script>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>

<script src="{{ asset('js/app.js') }}"></script>
<script>
    function showAlert(type,title,text) {

      Swal.fire({
        title: title,
        text: text,
        type: type,
        confirmButtonText: 'OK'
      });
    }

    function showConfirm(type,title,text,confirmButtonText,formId) {
        console.log("ruchini nneee",formId);
      Swal.fire({
        title: title,
        text: text,
        showCancelButton: true,
        confirmButtonText: confirmButtonText,
        showLoaderOnConfirm: true,
        customClass:{confirmButton: 'btn btn-danger',}
      }).then((result) => {
        
        if (result.value) {
            console.log("ruchinisss",formId);
          $("#delete_user_4").submit();
          return true;
        }
      });

    }
</script>

resources/views/includes/header.blade.php
<div class="nav-wrap">
    <nav class="navbar navbar-expand-lg navbar-light bg-light cust-nav">
        <a class="navbar-brand" href="">QUALITAPPS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="form-inline my-2 my-lg-0 ml-auto">
                <a href="" >
                    <span>{{Auth::user()->username}}</span>
                </a><br></br>
                <a href="{{url('api/logout')}}" class="profile-log-wrap">
                   <img src="{{asset("images/dp.png")}}"
                        class="img-fluid" alt="logo"/>
                   <span>LOGOUT</span>
               </a>
            </form>
        </div>
    </nav>
</div>

resources/views/includes/sidebar.blade.php
<div class="side-bar">
    <a class="side-nav-link {{(Request::segment(1)=='dashboard'&&Request::segment(2)==null)?$active='active':$active=''}}" href="{{route('dashboard.index')}}"><span><img src="{{asset("images/pay.png")}}" alt="side-bar-icon"></span>DASHBOARD</a>
    <a class="side-nav-link side-nav-link {{(Request::segment(1)=='user-management'&&Request::segment(2)==null)?$active='active':$active=''}}" href="{{route('reports.index')}}"><span><img src="{{asset("images/user.png")}}" alt="side-bar-icon"></span>Reports</a>
</div>